# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request_target:
    branches: [main, master]
    types: [labeled]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      REDCAP_URI: ${{ secrets.REDCAP_URI }}
      SUPERHEROES_REDCAP_API: ${{ secrets.SUPERHEROES_REDCAP_API }}
      REDCAPTIDIER_CLASSIC_API: ${{ secrets.REDCAPTIDIER_CLASSIC_API }}
      REDCAPTIDIER_CLASSIC_NOREPEAT_API: ${{ secrets.REDCAPTIDIER_CLASSIC_NOREPEAT_API }}
      REDCAPTIDIER_LONGITUDINAL_API: ${{ secrets.REDCAPTIDIER_LONGITUDINAL_API }}
      REDCAPTIDIER_LONGITUDINAL_NOREPEAT_API: ${{ secrets.REDCAPTIDIER_LONGITUDINAL_NOREPEAT_API }}
      REDCAPTIDIER_LONGITUDINAL_NOARMS_API: ${{ secrets.REDCAPTIDIER_LONGITUDINAL_NOARMS_API }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          clean: false
          branch: gh-pages
          folder: docs
